### ISSUE TITLE
Problem with L515

### ISSUE THREAD

**Issue by avgilias** [wh200720041/ssl_slam2#2]
Hello, first of all impresive work. 
I have my L515 connected and facing the following problem after running the " roslaunch ssl_slam ssl_slam_mapping.launch". 
![image](https://user-images.githubusercontent.com/73549825/112216402-2019aa00-8c2a-11eb-9d7a-2298c461d74a.png)

I am completely new in ROS. Thank you very much for your time.

**Comment by wh200720041** [comment]
Can you try 
```
rosrun rqt_graph rqt_graph
```
and 
```
rosrun rqt_tf_tree rqt_tf_tree
```

you can attach the results here

**Comment by avgilias** [comment]
Thank you for the reply. I am getting the message "Couldn't find ROS master. Either start 'roscore' or abort loading the plug in" I have the L515 directly connected on my laptop and I am getting the same problem in two different versions of Ubuntu 18.04 and 20.04 (with ROS melodic and noetic). 
Maybe I am missing something while trying to use your code.

**Comment by wh200720041** [comment]
You have to launch 
```
roslaunch ssl_slam ssl_slam_mapping.launch
```
before 
```
rosrun rqt_graph rqt_graph
```

**Comment by avgilias** [comment]
The graph for Melodic ROS version is 
<img width="1691" alt="graph" src="https://user-images.githubusercontent.com/73549825/112756461-f37cde00-8fed-11eb-8a2e-f2dd61da7848.png">
and for Noetic ROS version 
<img width="1226" alt="graph noetic" src="https://user-images.githubusercontent.com/73549825/112756476-02fc2700-8fee-11eb-8ab7-cf7237daee71.png">
and the tree is 
![tree](https://user-images.githubusercontent.com/73549825/112756492-13140680-8fee-11eb-858a-d832087a6824.png)

Really thank you for your support !

**Comment by wh200720041** [comment]
It seems that you did not publish correct laser points, the ssl_slam2 node does not subscribe to realsense camera. 

You can check the data from realsense by 
```
rostopic hz /camera/depth/color/points
 ```

**Comment by avgilias** [comment]
Thank you very much again
